#EXERCICE 1

# FROM nginx

# # informations utiles
# LABEL version="0.1"

# MAINTAINER responssable/créateur de l application 

# RUN rm -rf /usr/share/nginx/html/*

# WORKDIR /usr/share/nginx/html

# COPY . .

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]

#*****

# EXERCICE 2

# FROM nginx

# LABEL maintainer="Lazare"

# WORKDIR /usr/share/nginx/html

# RUN rm -rf /usr/share/nginx/html/

# RUN apt update && apt install git -y

# RUN git clone https://github.com/Lazarella/testDocker.git .

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]

# EXERCICE 3

FROM node AS BUILD

WORKDIR  /app

# variable d'environnement (changement dans la déclaration du port dans app.js)

ENV PORT=3002

COPY package*.json ./

RUN npm install 


COPY . . 

EXPOSE ${PORT} 

CMD [ "node","app.js" ]

# Commande pour construire l'image
# docker build -t todonode . --no-cache

# Commande pour le lancement d'un container avec cette image 
# docker run -p 5000:3001 todonode

#commande pour définir une variable d'environnement 
#docker run -e PORT=5000 -d -p 5005:5000 testenv
