  version: '3.8'

  services:
    db:
      image: mysql:8.0.36 
      container_name: local_mysqldb
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 123go
        MYSQL_DATABASE: yourdb 
      volumes:
        - local_mysqldb:/var/lib/mysql
        - ./scripts/amend_user.sql:/docker-entrypoint-initdb.d/amend_user.sql
      build:
        context: .
        dockerfile: dockerfile-db 

    adminer:
      depends_on:
        - bd
      image: adminer
      container_name: sqladmin_container
      restart: always
      ports:
        - "8080:8080"
      volumes:
        - sqladmin_container:/var/lib/sqladmin

    # phpmyadmin:
    # image: phpmyadmin
    # container_name: sqladmin_container
    # restart: always
    # ports:
    #   - 8080:80
    # environment:
    #   - PMA_ARBITRARY=1
    # volumes:
    #   - sqladmin_container:/var/lib/sqladmin

  volumes:
    local_mysqldb:
    sqladmin_container:

     

  
