
# FROM nginx

# # informations utiles
# LABEL version="0.1"

# MAINTAINER responssable/créateur de l application 

# RUN rm -rf /usr/share/nginx/html/*

# WORKDIR /usr/share/nginx/html

# COPY . .

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]

FROM nginx

LABEL maintainer="Lazare"

WORKDIR /usr/share/nginx/html

RUN rm -rf /usr/share/nginx/html/

RUN apt update && apt install git -y

RUN git clone https://github.com/Lazarella/testDocker.git .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]