version: '3.8'

services:
  db: 
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      -"5432:5432"
    environment:
      - POSGRES_USER: root
      - POSTGRES_PASSWORD: password
    volumes:
      -local_pgdb:/var/lib/postgresql/data
    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always
      ports:
        -"8888:80"
      environnement:
        PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
        PGADMIN_DEFAULT_PASSWORD: "password"
      volumes:
      - pgadmin-data:/var/lib/pgadmin


  volumes:
    local_pgdata:
    pgadmin-data: 

    #pour lancer compose : 
    # docker compose up -d 

